# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/Peridot-Development/kernel_xiaomi_peridot.git
          kernel-dir: msm-4.9-c1
          kernel-branch: peridot-u-oss
          config: microdroid_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          anykernel3: true
